spring.datasource.url=jdbc:postgresql://dpg-d8mot9po3t8c73c35md0-a/miniclinic_db_dlef
spring.datasource.username=miniclinic_db_dlef_user
spring.datasource.password=c0VBKIJxOhCh4sNp0KvaP4XA3oHg2Onq
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false